package com.wonder.wonder.cards;

/**
 * Creator: bm
 * Date: 13.06.17.
 */
public enum CardWonder {
// need do wonder class

    THE_COLOSSUS_OF_RHODES_SIDE_A,
    THE_LIGHTHOUSE_OF_ALEXANDRIA_SIDE_A,
    THE_TEMPLE_OF_ARTEMIS_IN_EPHESUS_SIDE_A,
    THE_HANGING_GARDENS_OF_BABYLON_SIDE_A,
    THE_STATUE_OF_ZEUS_IN_OLYMPIA_SIDE_A,
    THE_MAUSOLEUM_OF_HALICARNASSUS_SIDE_A,
    THE_PYRAMIDS_OF_GIZA_SIDE_A,
    THE_COLOSSUS_OF_RHODES_SIDE_B,
    THE_LIGHTHOUSE_OF_ALEXANDRIA_SIDE_B,
    THE_TEMPLE_OF_ARTEMIS_IN_EPHESUS_SIDE_B,
    THE_HANGING_GARDENS_OF_BABYLON_SIDE_B,
    THE_STATUE_OF_ZEUS_IN_OLYMPIA_SIDE_B,
    THE_MAUSOLEUM_OF_HALICARNASSUS_SIDE_B,
    THE_PYRAMIDS_OF_GIZA_SIDE_B;


    private String side;
    private GameResource startResourse;
    private Integer maxlevelBuild;

}
