version: 2
updates:
  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "gradle"

    # Allow up to 3 open pull requests from dependabot
    open-pull-requests-limit: 3

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"

    # Allow up to 3 open pull requests from dependabot
    open-pull-requests-limit: 3