-- MySQL Script generated by MySQL Workbench
-- сб, 29-лип-2017 17:30:24 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wonder
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wonder` ;

-- -----------------------------------------------------
-- Schema wonder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wonder` DEFAULT CHARACTER SET utf8 ;
USE `wonder` ;

-- -----------------------------------------------------
-- Table `wonder`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`user` ;

CREATE TABLE IF NOT EXISTS `wonder`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wonder`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`game` ;

CREATE TABLE IF NOT EXISTS `wonder`.`game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phase` VARCHAR(45) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wonder`.`user_in_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`user_in_game` ;

CREATE TABLE IF NOT EXISTS `wonder`.`user_in_game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `wonder` VARCHAR(255) NULL,
  `position` INT NOT NULL,
  `p_wars` INT NULL,
  `p_gold` DOUBLE NULL,
  `p_wonder` INT NULL,
  `p_blue` INT NULL,
  `p_yellow` INT NULL,
  `p_green` INT NULL,
  `p_purple` INT NULL,
  `p_debt` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_in_game_1_idx` (`user_id` ASC),
  INDEX `fk_user_in_game_game_id_idx` (`game_id` ASC),
  CONSTRAINT `fk_user_in_game_users_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `wonder`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_user_in_game_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `wonder`.`game` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wonder`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`event` ;

CREATE TABLE IF NOT EXISTS `wonder`.`event` (
  `id` INT NOT NULL,
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `userInGame_id` INT NOT NULL,
  `action_name` VARCHAR(255) NOT NULL,
  `phase` VARCHAR(255) NOT NULL,
  `card` VARCHAR(255) NOT NULL,
  `chain_card` VARCHAR(255) NULL,
  `gold_change` INT NULL DEFAULT 0,
  `debt` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_events_1_idx` (`game_id` ASC),
  INDEX `fk_events_2_idx` (`userInGame_id` ASC),
  CONSTRAINT `fk_events_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `wonder`.`game` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_events_2`
    FOREIGN KEY (`userInGame_id`)
    REFERENCES `wonder`.`user_in_game` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wonder`.`card_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`card_set` ;

CREATE TABLE IF NOT EXISTS `wonder`.`card_set` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `game_id` INT NOT NULL,
  `set_number` INT NULL,
  `age` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_set_1_idx` (`game_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_card_set_game_id`
    FOREIGN KEY (`game_id`)
    REFERENCES `wonder`.`game` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wonder`.`card_set_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wonder`.`card_set_item` ;

CREATE TABLE IF NOT EXISTS `wonder`.`card_set_item` (
  `id` INT NOT NULL,
  `userInGame_id` INT NOT NULL,
  `card_set_id` INT NOT NULL,
  `played_phase` VARCHAR(255) NOT NULL,
  `card` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_set_item_1_idx` (`card_set_id` ASC),
  INDEX `fk_card_set_item_user_id_idx` (`userInGame_id` ASC),
  CONSTRAINT `fk_card_set_item_card_set_id`
    FOREIGN KEY (`card_set_id`)
    REFERENCES `wonder`.`card_set` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_card_set_item_user_id`
    FOREIGN KEY (`userInGame_id`)
    REFERENCES `wonder`.`user_in_game` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
